#!/bin/bash
# This script is immediatelly executed by uwsgi during startup
# it prepares the prometheus_multiproc_dir folder to store the metrics from separate uwsgi workers (per PID)
set -ex

rm -Rf $1
mkdir -p $1
chmod 755 $1
if id -u nginx &>/dev/null; then
    chown $(id -u nginx):$(id -g nginx) $1
fi
