#!/bin/bash
# This script is immediatelly executed by uwsgi during startup
# it prepares the prometheus_multiproc_dir folder to store the metrics from separate uwsgi workers (per PID)
set -ex

rm -Rf $1
mkdir $1
chmod 755 $1
chown 100:101 $1
