from setuptools import setup, find_packages

setup(
    name='fence',
    version='0.2.0',
    # install_requires=[
    #     "Authlib[crypto]",
    #     "oauth2client",
    #     "addict",
    #     'boto',
    #     'botocore',
    #     "boto3",
    #     "cirrus",
    #     "cryptography",
    #     "flask-restful",
    #     "Flask",
    #     "Flask-CORS",
    #     "Flask_OAuthlib",
    #     "Flask_SQLAlchemy_Session",
    #     "google_api_python_client",
    #     "httplib2",
    #     "python-jose",
    #     "oauthlib",
    #     "psycopg2",
    #     "pysftp",
    #     "pytest-flask",
    #     "pytest",
    #     "bcrypt",
    #     "python_dateutil",
    #     "PyJWT",
    #     "requests",
    #     "six",
    #     "SQLAlchemy",
    #     "temps",
    #     "userdatamodel",
    #     "Werkzeug",
    #     "storageclient",
    #     "pyyaml"
    # ],
    scripts=[
        "bin/fence-create",
    ],
    packages=find_packages(),
)
