#!/usr/bin/env bash
# This script is called by:
#   UWSGI during startup, this gets moved to the /fence directory in the Dockerfile
#     - It prepares the prometheus_multiproc_dir folder to store the metrics from separate uwsgi workers (per PID)
#   run.py
#     - So local runs setup necessary environment vars and folders for prometheus metrics
#   Test framework in conftest
#     - So test runs setup necessary environment vars and folders for prometheus metrics


# Default directory if no argument is provided
DIR=${1:-/var/tmp/uwsgi_flask_metrics}

export PROMETHEUS_MULTIPROC_DIR="$DIR"

set -ex

rm -Rf "$DIR"
mkdir -p "$DIR"
chmod 755 "$DIR"
if id -u nginx &>/dev/null; then
    chown "$(id -u nginx)":"$(id -g nginx)" "$DIR"
fi
