name: Integration Tests

on: pull_request

jobs:
  integration_tests:
    name: Integration tests
    uses: uc-cdis/gen3-code-vigil/.github/workflows/shared_integration_tests.yaml@chore/cleanup_jenkins_references
    with:
      SERVICE_TO_TEST: fence
      TEST_REPO_BRANCH: chore/cleanup_jenkins_references
    secrets:
      CI_AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
      CI_AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      QA_DASHBOARD_S3_PATH: ${{ secrets.QA_DASHBOARD_S3_PATH }}
      CI_TEST_ORCID_USERID: ${{ secrets.CI_TEST_ORCID_USERID }}
      CI_TEST_ORCID_PASSWORD: ${{ secrets.CI_TEST_ORCID_PASSWORD }}
      CI_TEST_RAS_EMAIL: ${{ secrets.CI_TEST_RAS_EMAIL }}
      CI_TEST_RAS_PASSWORD: ${{ secrets.CI_TEST_RAS_PASSWORD }}
      CI_TEST_RAS_2_EMAIL: ${{ secrets.CI_TEST_RAS_2_EMAIL }}
      CI_TEST_RAS_2_PASSWORD: ${{ secrets.CI_TEST_RAS_2_PASSWORD }}
      CI_SLACK_BOT_TOKEN: ${{ secrets.CI_SLACK_BOT_TOKEN }}
      CI_SLACK_CHANNEL_ID: ${{ secrets.CI_SLACK_CHANNEL_ID }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
